workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

stages:
  - pre
  - release
  - post

include:
  - local: '.gitlab/workflows/release.yml'
  - local: '.gitlab/workflows/terraform-doc.yml'
