variables:
  MODULE_PATH: modules/ecs-asg-cluster

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'

stages:
  - pre
  - release
  - post

include:
  - local: '.gitlab/workflows/release.yml'
  - local: '.gitlab/workflows/terraform-doc.yml'
