include:
  - local: '.gitlab/workflows/docs.yml'
  - local: '.gitlab/workflows/release.yml'

workflow:
  rules:
    # 태그 이벤트에서 실행
    - if: '$CI_COMMIT_TAG'
      when: always

    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE !~ /chore\(release\)/'
      when: always

    - when: never


stages:
  - pre
  - docs
  - release
  - post
