
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always

stages:
  - pre
  - doc
  - release
  - post

include:
  - local: '.gitlab/workflows/release.yml'
  - local: '.gitlab/workflows/terraform-doc.yml'
