repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md"
      - id: check-added-large-files
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: end-of-file-fixer

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - "--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"
      - id: terraform_validate
        args:
          - "--tf-init-args=-upgrade"
          - "--hook-config=--retry-once-with-cleanup=true"
      - id: terraform_docs
        args:
          - "--hook-config=--path-to-file=README.md"
          - "--hook-config=--add-to-existing-file=true"
          - "--hook-config=--create-file-if-not-exist=true"
          - "--hook-config=--use-standard-markers=true"
          - "--args=--sort-by=required"
