stages:
  - docs

terraform-docs:
  stage: docs
  image:
    name: quay.io/terraform-docs/terraform-docs:latest
    entrypoint: ['']
  variables:
    TERRAFORM_PATH: modules/ecs-asg-cluster
    WORKFLOW_PATH: .gitlab/workflows
    DOCS_FILENAME: TERRAFORM.md
  script:
    - terraform-docs markdown table \
      --output-file=${DOCS_FILENAME} \
      --output-mode=replace \
      --sort=true \
      --sort-by=required \
      --hide-empty=true \
      --show-sensitive=true \
      --read-comments=true \
      --escape=false \
      --indent=2 \
      ${TERRAFORM_PATH}

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/
      changes:
        - 'modules/ecs-asg-cluster/**/*.tf'
        - '.gitlab/workflows/.terraform-docs.yml'
