stages:
  - docs

terraform-docs:
  stage: docs
  image:
    name: quay.io/terraform-docs/terraform-docs:latest
    entrypoint: ['']
  variables:
    TERRAFORM_PATH: modules/ecs-asg-cluster
    WORKFLOW_PATH: .gitlab/workflows
    DOCS_FILENAME: TERRAFORM.md
  script:
    - terraform-docs markdown table \
      --output-file=${DOCS_FILENAME} \
      --output-mode=replace \
      --sort=true \
      --sort-by=required \
      ${TERRAFORM_PATH}

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - '${TERRAFORM_PATH}/**/*.tf'
        - '${WORKFLOW_PATH}/.terraform-docs.yml'
