.default_branch: &default_branch
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.default_branch_skip_chore: &default_branch_skip_chore
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE !~ /^docs\(terraform\)/'

.rules:default_and_changes:
  rules:
    - <<: *default_branch
      changes:
        - ${MODULE_PATH}/**/*.tf

.rules:default_on_success:
  rules:
    - <<: *default_branch_skip_chore
      when: on_success
